---
pages:
  -
    ? "VaizrProfessionalPowerUI & Vaizr REST API"
    : index.md
  -
    ? "Professional Power UI"
    :
      -
         ? "Getting Started"
         : professionalpowerui/index.md
      -
         ? "From Ubuntu 14.04 to virtualdemobox"
         :  professionalpowerui/from_ubuntu_to_vaizrdemobox.md
      -
         ? ""
         : downloads/downloadvaizrdemobox.md
  -
    ? "Leave email for download vaizrdemobox"
    : downloads/leavemail.md
  -
    ? "Appendix"
    :
      -  
         ? "Onboarding"
         : appendix/onboarding.md
site_name: Vaizr Documentation
dev_addr: '0.0.0.0:8000'
theme: readthedocs
extra_javascript: [extra.js]