---
pages:
  -
    ? "VaizrProfessionalPowerUI & Vaizr REST API"
    : index.md
  -
    ? "Professional Power UI"
    :
      -
         ? "Getting Started"
         : professionalpowerui/gettingstarted.md
      -
         ? "Generate Screens"
         : professionalpowerui/masterdetail.md
  # -
  #   ? "Vaizr REST API"
  #   :
  #     -
  #        ? ""
  #        : restapi/index.md
  -
    ? "Appendix"
    :
      -
         ? "Leave email for download vaizrdemobox"
         : downloads/leavemail.md
      -  
         ? "Onboarding"
         : appendix/onboarding.md
      -  
         ? "Mac, Linux and X-Windows"
         : appendix/mac_xquartz.md
      -  
         ? "Windows and X-Windows"
         : appendix/windows_mobaxterm.md
      -
         ? "From Ubuntu 14.04 to virtualdemobox"
         :  appendix/from_ubuntu_to_vaizrdemobox.md
      -
         ? ""
         : downloads/downloadvaizrdemobox.md
site_name: Vaizr Documentation
dev_addr: '0.0.0.0:8000'
theme: readthedocs
extra_javascript: [extra.js]